version: 1.0.{build}
skip_tags: true
configuration: Release
platform: x86
environment:
  SolutionDirectory: .
before_build:
- cmd: >-
    sed -i "s#$(SolutionDir)#.#g" PoGo.NecroBot.Logic.csproj

    nuget restore -OutputDirectory packages

    sed -i "s#$(SolutionDir)#.#g" PokemonGo.RocketAPI.csproj

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git PokemonGo.RocketAPI

    sed -i "s#$(SolutionDir)#..#g" PokemonGo.RocketAPI/PokemonGo.RocketAPI.csproj

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos

    sed -i "s#$(SolutionDir)#..#g" POGOProtos/POGOProtos.csproj
build:
  project: PoGo.NecroBot.Logic.csproj
  verbosity: minimal