version: 1.0.{build}
skip_tags: true
configuration: Release
platform: x86
# clone directory
clone_folder: c:\projects\Logic
#
environment:
  SolutionDirectory: .
before_build:
- cmd: >-
    sed -i "s#$(SolutionDir)#./PoGo.NecroBot.Logic#g" PoGo.NecroBot.Logic.csproj

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git FeroxRev

    sed -i "s#$(SolutionDir)#..#g" FeroxRev/PokemonGo.RocketAPI.csproj

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos

    sed -i "s#$(SolutionDir)#..#g" POGOProtos/POGOProtos.csproj

    nuget restore -OutputDirectory packages
build:
  project: PoGo.NecroBot.Logic.csproj
  verbosity: minimal