version: 1.0.{build}
skip_tags: true
configuration: Release
platform: x86
environment:
  SolutionDirectory: .
before_build:
- cmd: >-
    sed -i $(SolutionDirectory)PoGo.NecroBot.Logic.csproj

    nuget restore -OutputDirectory packages

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos

    sed -i $(SolutionDirectory)POGOProtos/POGOProtos.csproj

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git FeroxRev

    sed -i $(SolutionDirectory)FeroxRev/PokemonGo.RocketAPI.csproj
build:
  project: PoGo.NecroBot.Logic.csproj
  verbosity: minimal