version: 1.0.0.{build}
skip_tags: true
configuration: Release
platform: x86
# environment variables
environment:
  SolutionDirectory: .
install:
- git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos
- git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git FeroxRev
before_build:
before_build:
  - nuget restore
build:
  verbosity: minimal
