version: 1.0.0.{build}
skip_tags: true
configuration: Release
platform: x86
# environment variables
environment:
  SolutionDirectory: .
before_build:
- cmd: >-
    sed -i "s#$(SolutionDir)#.#g" PoGo.NecroBot.Logic.csproj
    nuget restore -OutputDirectory packages
    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos
    sed -i "s#$(SolutionDir)#..#g" POGOProtos/POGOProtos.csproj
    sed -i "s#$(SolutionDir)#...#g" PokemonGo.RocketAPI.csproj
    nuget restore -OutputDirectory packages
    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git FeroxRev
    sed -i "s#$(SolutionDir)#....#g" FeroxRev/PokemonGo.RocketAPI.csproj
build:
  verbosity: minimal
